GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2luZ2giLCJpYXQiOjE2NDkyNzQ0NzQsImV4cCI6MTY0OTI3NDQ5NH0.WA79_jiWAT841x0nCPRPGAp8TknF-8_a8kXxnxm6nlk

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2luZ2giLCJpYXQiOjE2NDkyNzQ4MTZ9.50HutkGSC_yBjKY17yTChlXMuW3QlVqXvaV0CLM4HWk"
}
###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2luZ2giLCJpYXQiOjE2NDkyNzQ4MTZ9.50HutkGSC_yBjKY17yTChlXMuW3QlVqXvaV0CLM4HWk"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"singh"
}